#!/bin/bash
# Regenerates nginx/cloudflare.conf from Cloudflare's published ranges so the
# real player address is taken from CF-Connecting-IP and rate limits key on it.
set -euo pipefail

target="$(dirname "$0")/../nginx/cloudflare.conf"
{
    echo "# Generated by scripts/cloudflare_ips.sh on $(date -u +%F). Do not edit."
    for list in ips-v4 ips-v6; do
        curl -fsS "https://www.cloudflare.com/${list}" | awk 1 | sed 's/^/set_real_ip_from /; s/$/;/'
    done
    echo "real_ip_header CF-Connecting-IP;"
} > "$target"
echo "Wrote ${target}."
